### ISSUE TITLE
Release ros-jade-resource-retriever

### ISSUE THREAD

**Issue by 130s** [ros/robot_model#104]
[ar_track_alvar needs it](https://github.com/sniekum/ar_track_alvar/issues/46). Thanks!

**Comment by fspindle** [comment]
vision_visp needs it also.

**Comment by wjwwood** [comment]
I've release `resource_retriever` for Jade:

ros/rosdistro#8026

I also moved it to it's own repository:
- https://github.com/ros/resource_retriever.git
- https://github.com/ros/robot_model/commit/210654ace651646b87c2849e96ef8f391bd76ad1

And updated the release in Indigo to reflect this (it had already been released separately through some magic):

ros/rosdistro#8025

**Comment by isucan** [comment]
Thank you William!
