### ISSUE TITLE
Release 1.11.8?

### ISSUE THREAD

**Issue by 130s** [ros/robot_model#109]
I'm interested in testing https://github.com/ros/robot_model/pull/108. Thanks!

**Comment by 130s** [comment]
[This question](http://answers.ros.org/question/209686/turtlebot-apt-get-update-has-generated-an-error-on-minimallaunch/) might also be related to the latest commit that's not yet released.

DEB is required in some tests in the downstream that's why the new release into rosdistro is necessary.

**Comment by 130s** [comment]
Is there any blocker for this? @isucan

**Comment by 130s** [comment]
ping @wjwwood

**Comment by wjwwood** [comment]
This is up to @isucan. If he asks me to release it I can try to get to it sometime this week.

**Comment by isucan** [comment]
I think we can release this, yes.  @wjwwood -- if you can do this, i would be very grateful.

**Comment by mistoll** [comment]
Any news on this? A new release would be very helpful.

**Comment by wjwwood** [comment]
Indigo: https://github.com/ros/rosdistro/pull/9433
Jade: https://github.com/ros/rosdistro/pull/9434
