### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by scpeters** [ros/robot_model#120]
I've just started testing a travis build script in my fork:
- https://github.com/scpeters/robot_model/blob/travis/.travis.yml
- https://travis-ci.org/scpeters/robot_model/builds/96232448

I need a ROS admin to enable travis CI for this repo.

**Comment by wjwwood** [comment]
I believe it is already enabled, but I'm not sure if someone else beat me to it or it has been on for a while.

**Comment by scpeters** [comment]
Thanks!
