### ISSUE TITLE
Kinetic Release

### ISSUE THREAD

**Issue by wjwwood** [ros/robot_model#126]
Can this be released into Kinetic (even just initially)? It's blocking a first release of `rviz`.

**Comment by jackieokay** [comment]
This repo is blocked by geometric_shapes and random_numbers. They are pretty stable, but just in case I will ping @davetcoleman, @mikeferguson etc--is it okay if we release those packages into Kinetic?

**Comment by jackieokay** [comment]
asking for forgiveness instead of permission here:
https://github.com/ros/rosdistro/pull/10992
https://github.com/ros/rosdistro/pull/10993

@wjwwood I'll release robot_model now. Cheers.

**Comment by jackieokay** [comment]
initial release is done: https://github.com/ros/rosdistro/pull/10994

I'll release again if/when I finish those features I was trying to get into Kinetic. :)

**Comment by wjwwood** [comment]
Thanks!
