### ISSUE TITLE
when I install ros

### ISSUE THREAD

**Issue by Tom-Shen** [ros/robot_model#131]
# I got belwo error, what should I do?

==> Processing catkin package: 'collada_urdf'
==> Building with env: '/opt/ros/indigo/env.sh'
Makefile exists, skipping explicit cmake invocation...
==> make cmake_check_build_system in '/home/pi/ros_catkin_ws/build_isolated/collada_urdf'
==> make -j4 -l4 in '/home/pi/ros_catkin_ws/build_isolated/collada_urdf'
[ 33%] Built target collada_to_urdf
[ 66%] Built target collada_urdf
Linking CXX executable /home/pi/ros_catkin_ws/devel_isolated/collada_urdf/lib/collada_urdf/urdf_to_collada
/usr/bin/ld: cannot find -lcollada-dom2.4-dp

**Comment by jackieokay** [comment]
Hey @Tom-Shen,

Please ask questions like this on ROS Answers: http://answers.ros.org/questions/

Here are some initial ideas:

From your other question, it looks like you are compiling ROS Indigo on Raspberry Pi 3, is that correct?

Which version of the collada-dom system package do you have installed? Try a `dpkg -l | grep collada` to see.

Which OS are you running (Raspbian or Ubuntu)? collada-dom might not be available for Raspbian, I'm not sure off the top of my head.

If this doesn't help, make a question ROS Answers and someone will continue helping you there.
