### ISSUE TITLE
collada_urdf: Box geometries appear to have wrong size

### ISSUE THREAD

**Issue by skohlbr** [ros/robot_model#132]
As also previously noted on the [OpenRAVE mailing list](http://openrave-users-list.185357.n3.nabble.com/Box-geometry-in-URDF-does-not-scale-in-DAE-td4027346.html), it appears that box geometries are parsed not correctly, resulting in box geometries having half the size they should. See screenshots below for illustration:

URDF in rviz:
![urdf](https://cloud.githubusercontent.com/assets/205963/14812000/6fa546de-0b9b-11e6-92cc-bceae1e6cceb.png)

Generated DAE in Blender:
![collada](https://cloud.githubusercontent.com/assets/205963/14812012/7c029260-0b9b-11e6-8d44-bddf22e0049d.png)

Note that all box geometries are scaled wrongly, while all mesh geoms look correct.

This is using Ubuntu 14.04/AMD64/Indigo/latest collada_urdf from .debs.

**Comment by jackieokay** [comment]
thanks for reporting this; I opened #133 as a potential fix.

**Comment by clalancette** [comment]
I just pushed Jackie's fix into the upstream repository, which should fix this problem.  If you are still having problems, please feel free to re-open this issue.
