### ISSUE TITLE
resource_retriever: Add support for param:// to use ROS param

### ISSUE THREAD

**Issue by eacousineau** [ros/robot_model#17]
It would be nice to have a param:// protocol as well, so that the contents of an URDF could be set to something like 'param:///robot_description' or 'package://my_robot/urdf/robot.urdf'.

If putting that in complicates things (since it requires the ROS be init'd), then there could be an extra boolean flag to make it explicit (and error out if param:// is requested without that flag).

If others are interested, I could implement that feature.

**Comment by isucan** [comment]
I am not sure we should have this in resource_retriever. One issue is that roscpp would be an added as a dependency. Another is, if someone has a URDF file that uses the param:// specification for resource, that may or may not be valid, depending on the state of the system.

**Comment by eacousineau** [comment]
Given that resource_retriever already supports curl, there is already a risk about the configuration of the system. Even though param:// might be more volatile, I don't think that risk would increase considerably.

I think I understand  your point about not involving roscpp. Just to clarify, is it because it involves so many other components that do not fall within the scope of resource_retriever?

I would still like to have the possible support of param:// though. A few possible options:
1. Extend the class with something like "ParamEnabledRetriever".
2. Make a custom handler registry system, initialized statically, error out on conflicts (if multiple libs want to support same protocol), allow forced override. This would make things much more volatile from system to system though.
3. See how coupled ros::getParam() is to the rest of roscpp, potentially separate it out.

Item 1 would be the most practical for small changes that would not affect much else. I will go ahead and implement that in an offshoot package.

**Comment by sloretz** [comment]
It looks like resource_retriever was moved some time ago. I've moved this issue to ros/resource_retriever#12
