### ISSUE TITLE
Use of multiple collision geometries in URDF models

### ISSUE THREAD

**Issue by skohlbr** [ros/robot_model#18]
As talked about at ROScon, multiple collision geometries have been added to the Atlas robot model and are currently used within the DRC project. This change apparently hasn't been coordinated with Ioan, who was pretty surprised (and not amused ;) ) about this.

This new feature certainly is useful. Unfortunately some existing tools like self_filter or MoveIt! planning will silently degrade in performance, as they currently only use the first defined collision object defined for a link and ignore all others (so they still "kind of" work, just not correctly).

Thus, inclusion of this addition into URDF should be discussed (and appropriate steps taken). As can be seen from tickets below, for example rviz already has been patched without prior coordination with the robot_model maintainer.

Some DRC related tickets:
https://bitbucket.org/osrf/drcsim/issue/255/atlas-urdf-and-sdf-collision-geometries
https://github.com/ros-visualization/rviz/issues/633

**Comment by isucan** [comment]
We have talked amongst ourselves since, and I will implement this feature in MoveIt. We need to clarify things a little on what exactly the additions to URDF are (we need to document this feature). I will try to work on this in the next few days.

**Comment by skohlbr** [comment]
Whenever one loads a Atlas model with multiple collision geometries, a lot of warnings like this are flooding the terminal:

<pre>
[ WARN] [1381924319.710257609]: The notion of a group name for collision tags is not supported by URDF.
[ WARN] [1381924319.710280748]: The notion of a group name for collision tags is not supported by URDF.
[ WARN] [1381924319.710323033]: The notion of a group name for collision tags is not supported by URDF.
[ WARN] [1381924319.710382770]: The notion of a group name for collision tags is not supported by URDF.
</pre>

I this something we have to live with because the Atlas model is using tags outside the URDF specification? I´m asking because we have quite a few URDF reading nodes and these warnings seriously clutter up the terminal on startup, making other output hard to see.

**Comment by isucan** [comment]
The URDF spec allows multiple collisions, but the name of the group is not currently included in the spec. So, it is possible to use multiple visual tags, multiple collision tags, but not to name them using the group attribute. The message you see is just a warning asking to remove the group attribute from the collision tags.

**Comment by skohlbr** [comment]
Ah ok, makes sense. So I gather by just removing the group tags this error will go away. That´s good enough for me, thanks :)
