### ISSUE TITLE
Lunar Release

### ISSUE THREAD

**Issue by mikaelarguedas** [ros/robot_model#194]
Hi @clalancette and @sloretz,

All dependencies of `robot_model` are now released in ROS Lunar :tada: !

Could you please release 1.12.8 in Lunar to unlock the release of the [downstream repos](http://repositories.ros.org/status_page/blocked_releases_lunar.html?q=id%3D%22robot_model%22&s=6&r=1) ? Thanks!

**Comment by sloretz** [comment]
On it

**Comment by mikaelarguedas** [comment]
All green now, thanks @sloretz , closing this
