### ISSUE TITLE
KDL variables not used correctly

### ISSUE THREAD

**Issue by mxsrc** [ros/robot_model#199]
The current kdl_parers/CMakeLists.txt does not use the variables set by orocos_kdl correctly. According to the current [KDLConfig.cmake.in](https://github.com/orocos/orocos_kinematics_dynamics/blob/master/orocos_kdl/KDLConfig.cmake.in) orocors_kdl_LIBRARY_DIRS is not set at all, such that the find_library call will fail.

**Comment by sloretz** [comment]
Merged. Thanks!
