### ISSUE TITLE
The dae file can't be load which use collada_urdf to convert in ros

### ISSUE THREAD

**Issue by tcjcxy30** [ros/robot_model#204]
Hi:
   I use the collada_urdf to convert my urdf to a ".dae" file. It's can be seen in blender.
   When I load this ".dae" file to ros with c++ by the code 
   " marker.mesh_resource = "package://myrobot/meshes/sum_ur/sum_ur.dae";  "
   I get a error :
   Could not load resource [package://myrobot/meshes/sum_ur/sum_ur.dae]: Collada: package:
//myrobot/meshes/sum_ur/sum_ur.dae - Unsupported vertex referencing scheme
   Why would this happen? I use 16.04 and the "sum_ur" file is 28.8MB.
   Can you help me please.

**Comment by sloretz** [comment]
Hi @CxyCH, The `collada_urdf` package lives in another repo. Would you mind opening an issue there? https://github.com/ros/collada_urdf
