### ISSUE TITLE
Old release on Debian Jessie with Kinetic?

### ISSUE THREAD

**Issue by bmagyar** [ros/robot_model#208]
Hi everyone,

I've recently released a package that depends on urdf and found that builds keep failing on both debian jessie platforms.
Take a look:
http://build.ros.org/job/Kbin_djv8_dJv8__urdf_geometry_parser__debian_jessie_arm64__binary/8/

It seems as if the release for debian jessie was an old one, all other builds are fine.

**Comment by clalancette** [comment]
This should be fixed by ros-controls/urdf_geometry_parser#6 .  I'm going to close this ticket out in favor of that PR; feel free to reopen if you are still having problems after that.
