### ISSUE TITLE
Is pcrecpp needed by urdf on indigo-devel?

### ISSUE THREAD

**Issue by sloretz** [ros/robot_model#215]
Urdf finds pcrecpp on indigo, but not on kinetic. Is this library used at all?

https://github.com/ros/robot_model/blob/50d4f2311fe16a1aa26699d0a66369b226d7a0df/urdf/CMakeLists.txt#L14

**Comment by clalancette** [comment]
I did a fairly comprehensive review here, and as far as I can tell, it is not used at all.  I'm going to open a PR to remove it.

**Comment by sloretz** [comment]
Fixed by #216
