### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Michaelyangyu** [ros/robot_model#225]
Hi
I get the following errors and I can't find the error. The command used is:
rosrun collada_urdf urdf_to_collada "$MYROBOT_NAME".urdf "$MYROBOT_NAME".dae

I got this error: Segmentation fault (core dumped)

I'm using ubuntu18.04  ,ROS  melodic .
Could you help me with it?
Thanks a lot.

**Comment by clalancette** [comment]
Please don't open duplicate issues on separate repositories.  This repository is actually dormant now, and has been split into component parts, so I'm going to go ahead and close this.
