### ISSUE TITLE
ros-groovy-resource-retriever and gdal

### ISSUE THREAD

**Issue by PierrickKoch** [ros/robot_model#37]
The .deb should depend on `libcurl-ssl-dev` and not `libcurl4-openssl-dev`, that conflicts with `libcurl4-gnutls-dev` which GDAL depends on.

[ http://wiki.ros.org/resource_retriever points this as the issue tracker ]

**Comment by wjwwood** [comment]
@pierriko for which versions of Ubuntu? This is a problem with the rosdep rule, this package depends on the `curl` rosdep rule:

https://github.com/ros/robot_model/blob/hydro-devel/resource_retriever/package.xml#L24

Which is defined here:

https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L350

If this is the appropriate solution then it will take place in the above repository as a change in the rosdep rule.

**Comment by PierrickKoch** [comment]
On Ubuntu (12.04+), `libgdal1-dev` depends on `libcurl4-gnutls-dev` [1]
I've sent a report on launchpad as well [2]

[1] http://packages.ubuntu.com/precise/libgdal1-dev
[2] https://bugs.launchpad.net/bugs/1224184

**Comment by PierrickKoch** [comment]
EDIT: It's actually due to their dependency on libdap which depends strictly on libcurl4-gnutls-dev

... https://bugs.launchpad.net/ubuntu/+source/libdap/+bug/1074104

**Comment by sloretz** [comment]
Looks like this is a groovy specific issue. Since Groovy is EOL I will close this issue. Feel free to reopen if it still applies to indigo, jade, or kinetic.
