### ISSUE TITLE
Latest release into Groovy (1.9.36) of robot_model has ABI-breaking changes

### ISSUE THREAD

**Issue by ahendrix** [ros/robot_model#39]
The latest release of robot_model has ABI breaking changes, which causes downstream packages and locally compiled programs to break.

Please revert to 1.9.35 or re-release it as 1.9.37, and stage these changes into the next release.

**Comment by isucan** [comment]
Can you be a bit more specific as to which change causes the ABI break? As far as I can see the differences between 1.9.35 and 1.9.36 are just bugfixes.

**Comment by ahendrix** [comment]
Agreed; I don't see anything in that diff that could have caused an ABI-breaking change.

My specific observation was that a version of robot_state_publisher compiled against kdl_parser 1.9.35 segfaults when run against 1.9.36. Unfortunately, this was one of our production systems that we're in a rush to get out, so I upgraded it and can no longer reproduce the problem. (I ran it in GDB and the top frame in the backtrace was inside of libkdl_parser)
