### ISSUE TITLE
Compiling in Gentoo

### ISSUE THREAD

**Issue by focs** [ros/robot_model#40]
Hi,
I was trying to collada_urdf on gentoo and I hat some problems linking with the collada library. 

First I installed version 2 but in my system they where installed in include/collada/... so the includes in collada_urdf.cpp should be something like:
# include <collada/assimp.hpp>

As I didn't want to edit the file and I saw version 3 is also accepted so I installed it but cmake still thought I was using version 2, I edited the CMakeFile in order to force version 3 and all went fine.

  #if( ${ASSIMP_VERSION} STRGREATER "2.0.0" )
    set(IS_ASSIMP3 1)
    add_definitions(-DIS_ASSIMP3)
  #endif()
  include_directories(${ASSIMP_INCLUDE_DIRS})
  link_directories(${ASSIMP_LIBRARY_DIRS})

Maybe there is a problem with the string comparation?

If you need me to test anything else please let me know.

Thanks.

**Comment by Antagonistic** [comment]
I needed to do something similar, only in my case setting the version in the CMakeCache.  

Can confirm bug still exists.

**Comment by focs** [comment]
I am using hydro on gentoo now and, so far, everything compiles without much problem.

**Comment by jackieokay** [comment]
Closing this issue since it sounds like it's resolved.
