### ISSUE TITLE
Uninitialized value in urdf::Geometry

### ISSUE THREAD

**Issue by florent-lamiraux** [ros/robot_model#41]
Hello,

Checking my code with valgrind I got an error:
  Conditional jump or move depends on uninitialised value(s)

After investigating, it seems that the empty constructor of
::urdf::Geometry does not initialize the field "type".

I am using groovy provided by ubuntu-12.04 32bits.

**Comment by isucan** [comment]
Can you by any chance point to where the condition was triggered?

**Comment by florent-lamiraux** [comment]
It is in some code developed in my lab
https://github.com/laas/hpp-model-urdf/blob/master/src/rcpdf/parser.cc, line 90.

From what I understand, line 160 of the same file,
rcpdfModel_ = ::rcpdf::parseRCPDF (contactsDescription);
calls a method defined in robot_contact_point
https://github.com/laas/robot_contact_point/blob/master/rcpdf/src/parser.cpp, line 134.

The uninitialized data is constructed line 122:
contact->geometry_ = parseGeometry(geometry_xml);

I can send you the rcpdf file parsed in a private message since the data belongs to Kawada Robotics and is confidential.

**Comment by isucan** [comment]
fixed here
https://github.com/ros/urdfdom_headers/commit/e0a24b2a801ede991d546001b024a93708313912
