### ISSUE TITLE
reqeust for release of new version

### ISSUE THREAD

**Issue by k-okada** [ros/robot_model#42]
current deb package (1.10.5) produces error when we use collada model file with robot_state_publisher. if we use current hydro-devel that contains following commi, it's ok. So I request to release new version for deb package.

https://github.com/ros/robot_model/commit/9ac73acff67fb59f4c391710535dd888359c5f91

**Comment by 130s** [comment]
Is this being reviewed? Some of our packages are awaiting for the new release of `robot_model`. Thank you!

**Comment by isucan** [comment]
released 1.10.16:
https://github.com/ros/rosdistro/pull/2580

**Comment by k-okada** [comment]
thanks!!!!
