### ISSUE TITLE
joint_state_publisher missing in the groovy-dev branch

### ISSUE THREAD

**Issue by vlsd** [ros/robot_model#46]
The ROS Wiki says here http://wiki.ros.org/joint_state_publisher that `joint_state_publisher` is included in the `groovy-dev` branch but it doesn't seem to be there. Am I missing something or is the Wiki wrong?

**Comment by bchretien** [comment]
:+1:

**Comment by wjwwood** [comment]
It is a bizzare setup indeed:

https://github.com/ros/robot_model/tree/groovy-devel/visualization

It is in a rosbuild stack, which is in a peer folder to the rest of robot_model which is catkin.

@isucan @DLu what's going on here?

**Comment by isucan** [comment]
Hey William,

This was the setup until (and including groovy). In hydro the package got
moved to robot_model. This change was way after the release of groovy
though, and was not backported to groovy.

Ioan

**Comment by vlsd** [comment]
Cool, I don't know why but the GitHub search seems to only look into the `hydro-devel` branch, and that mixed with a change of directories tripped me up. Thanks!

**Comment by vlsd** [comment]
@isucan so what is the proper way to install groovy-devel then? running `catkin_make` installs all the catkinized stuff but does not install `joint_state_publisher`. Does the visualization stack need to be installed separately?

**Comment by isucan** [comment]
You need to install the visualization stack separately. You can just get the .deb for that.

**Comment by vlsd** [comment]
The .deb is an older version of the script unless there's an unofficial deb floating around somewhere. I installed it manually by moving the `visualization` folder to `<prefix>\stacks\`and that seems to work. Is there a way to automate this during the `catkin_make install` process?

**Comment by jackieokay** [comment]
I'm closing this issue, since it's only relevant to developers who want to install a source build for Groovy, which is an increasingly shrinking group since Groovy was EOL'd in 2014.
