### ISSUE TITLE
robot_state_publisher support array of URDF strings

### ISSUE THREAD

**Issue by mikepurvis** [ros/robot_model#48]
Would be great if either a) the node could be run multiple times (with a namespaced robot_description parameter), or b) the node could accept multiple strings and unify them to a single large model.

Previous external efforts:

Compose urdf by [globbing together xacros into a file of include tags](https://github.com/clearpathrobotics/robot_upstart/blob/hydro-devel/scripts/mkxacro#L30).

Compose urdf using [yaml files defining known accessories and a GUI tool](https://github.com/LucidOne/iheart-ros-pkg/tree/master/ihe_hardware/urdf_compose).

**Comment by sloretz** [comment]
@mikepurvis This issue is now located here ros/robot_state_publisher#77
