### ISSUE TITLE
KDL vs. Gazebo: Inertia in the root link

### ISSUE THREAD

**Issue by isucan** [ros/robot_model#6]
KDL does not support inertia in the root link. So far one just left out the inertia specification in the URDF for the root link (as done  here). Unfortunately, this now causes a crash, if somebody is using Gazebo in Fuerte (e.g.:  turtlebot simulation).

To me this seems to be a design mismatch between KDL and Gazebo. Any idea how to align both?

Remark: Would be interesting, why root link inertia is now required in Gazebo and wasn't before.

**Comment by isucan** [comment]
https://kforge.ros.org/turtlebot/trac/ticket/138
http://answers.ros.org/question/38465/fuerte-turtlebot-simulator-ubuntu-1204-precise/

**Comment by isucan** [comment]
Possible fix:  https://code.ros.org/trac/ros-pkg/ticket/5512

**Comment by sloretz** [comment]
Hi @isucan, kdl_parser and kdl_parser_py have a [new location](https://github.com/ros/kdl_parser). It looks like this is a pretty old issue. Does it still apply? If so, would you mind creating it again [here](https://github.com/ros/kdl_parser)? In the meantime I'll close the issue here.
