### ISSUE TITLE
collada_urdf: Fails with assimp3

### ISSUE THREAD

**Issue by jbohren** [ros/robot_model#65]
Apparently `assimp.hpp` no longer exists in assimp3.

Probably needs a patch similar to:
https://code.ros.org/trac/ros-pkg/attachment/ticket/5498/rviz_assimp2_to_assimp3.patch
https://code.ros.org/trac/ros-pkg/attachment/ticket/5498/rviz_enable_assimp3.patch

**Comment by jackieokay** [comment]
on Ubuntu 14.04 with Indigo and libassimp3, collada_urdf is working for me. I think @cottsay fixed these issues in #53 and related PRs. Closing this issue.
