### ISSUE TITLE
wrong  lib options for urdf (and others)

### ISSUE THREAD

**Issue by k-okada** [ros/robot_model#76]
HI, currently `pkg-config --libs urdf` returns `-l` with  `-l:/xxx` not `-l/xxx` thats breaks downstream packages. i'm not if 1.10.19 fixed this problem, but need new release. I think current release is http://jenkins.ros.org/job/ros-hydro-urdf_sourcedeb/ 1.10.18.

```
$ pkg-config --libs urdf
-L/opt/ros/hydro/lib -lurdf -l:/opt/ros/hydro/lib/liburdfdom_sensor.so -l:/opt/ros/hydro/lib/liburdfdom_model_state.so -l:/opt/ros/hydro/lib/liburdfdom_model.so -l:/opt/ros/hydro/lib/liburdfdom_world.so -lrosconsole_bridge -lroscpp -l:/usr/lib/libboost_signals-mt.so -l:/usr/lib/libboost_filesystem-mt.so -lrosconsole -lrosconsole_log4cxx -lrosconsole_backend_interface -l:/usr/lib/liblog4cxx.so -l:/usr/lib/libboost_regex-mt.so -lxmlrpcpp -lroscpp_serialization -lrostime -l:/usr/lib/libboost_date_time-mt.so -l:/usr/lib/libboost_system-mt.so -l:/usr/lib/libboost_thread-mt.so -lpthread -lcpp_common -l:/opt/ros/hydro/lib/libconsole_bridge.so

$ LANG=C aptitude show ros-hydro-urdf
Package: ros-hydro-urdf                  
New: yes
State: installed
Automatically installed: no
Version: 1.10.18-1precise-20140617-0608-+0000
Priority: extra
Section: misc
Maintainer: Ioan Sucan <isucan@gmail.com>
Architecture: amd64
Uncompressed Size: 251 k
Depends: libboost-filesystem1.46.1 (>= 1.46.1-1), libboost-system1.46.1 (>= 1.46.1-1), libc6 (>= 2.14), libgcc1 (>=
         1:4.1.1), libstdc++6 (>= 4.6), libtinyxml2.6.2, ros-hydro-pluginlib, ros-hydro-rosconsole-bridge,
         ros-hydro-roscpp, ros-hydro-urdf-parser-plugin, ros-hydro-urdfdom, ros-hydro-urdfdom-headers
Conflicts: ros-hydro-urdf
Description: This package contains a C++ parser for the Unified Robot Description Format (URDF), which is an XML format for representing a robot model. The code API of the parser has been through our review process and will remain backwards compatible in future releases.

Homepage: http://ros.org/wiki/urdf


```

**Comment by wjwwood** [comment]
Are you on OS X or Linux?

**Comment by k-okada** [comment]
I'm using ubuntu 12.04 hydro, it seems catkin bug????

**Comment by wjwwood** [comment]
I'm pretty sure that is done on purpose to preserve ordering, but I remember it being an issue specifically with rosbuild on top of catkin on OS X, though I don't remember it being an issue with Linux.

@dirk-thomas do you have any insight on this.

**Comment by dirk-thomas** [comment]
I guess you refer to https://github.com/ros/catkin/issues/300 (specifically https://github.com/ros/catkin/commit/b6e6239a291c6d61cb99f181f5a6aaa1e3ffa612) which is necessary to prevent pkg-config from reordering the libraries.

**Comment by k-okada** [comment]
please check lib/pkgconfig/urdf.pc of http://packages.ros.org/ros-shadow-fixed/ubuntu/pool/main/r/ros-hydro-urdf/ros-hydro-urdf_1.10.18-1precise-20140617-0608-+0000_amd64.deb, it contains

```
Libs: -L/opt/ros/hydro/lib -lurdf -l:/opt/ros/hydro/lib/liburdfdom_sensor.so -l:/opt/ros/hydro/lib/liburdfdom_model_state.so -l:/opt/ros/hydro/lib/liburdfdom_model.so -l:/opt/ros/hydro/lib/liburdfdom_world.so -l:/opt/ros/hydro/lib/libconsole_bridge.so -l:/usr/lib/libboost_thread-mt.so -lpthread
```

I think '-l:/opt' is invalid, it should be '-l/opt'

**Comment by wjwwood** [comment]
That's my point, I don't think `-l:/path/to/libsomething.so` is invalid, from the man page for `ld`:

> -l namespec
> If namespec is of the form :filename, ld will search the library path for a file called filename, otherwise it will search the library path for a file called libnamespec.a.

This is not the case for OS X's BSD version of `ld`, which was a problem. It should not be an issue for `ld` on Linux.

**Comment by k-okada** [comment]
ok, thanks, sorry for bother you. I'll check my code....

**Comment by wjwwood** [comment]
There may be some other issue with it, so if you find something let us know.
