### ISSUE TITLE
Compile on indigo build firm failing 

### ISSUE THREAD

**Issue by k-okada** [ros/robot_model#78]
Hi

Buildfirm keep failing. Since urdf_heades is provided as non-catkin package, should we remove urdf_headeds from find_package(catkin...)?

http://jenkins.ros.org/view/IbinT64/job/ros-indigo-urdf-parser-plugin_binarydeb_trusty_amd64/

**Comment by wjwwood** [comment]
https://github.com/ros/robot_model/pull/77
https://github.com/ros/rosdistro/issues/4633

**Comment by k-okada** [comment]
Sorry, I should search issue list

**Comment by wjwwood** [comment]
That's ok, I was just pointing you to the related stuff.
