### ISSUE TITLE
Fix "SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'"

### ISSUE THREAD

**Issue by sromberg** [ros/robot_model#88]
When using the joint_state_publisher ROS since Indigo logs a warning:

```
[12:56:30] /opt/ros/indigo/lib/joint_state_publisher/joint_state_publisher:116: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
```

Please fix it to  reduce information overhead.

**Comment by wjwwood** [comment]
I think this has already been fixed:

https://github.com/ros/robot_model/blob/indigo-devel/joint_state_publisher/joint_state_publisher/joint_state_publisher#L116

https://github.com/ros/robot_model/commit/01a7ea91391161e306ae7e0d67912071808149e2

It may have just not been released yet.

**Comment by davetcoleman** [comment]
bump, this package needs to be released to get this fix. @isucan ?

**Comment by isucan** [comment]
will do soon

**Comment by jackieokay** [comment]
This has been fixed. I no longer see the warning.
