### ISSUE TITLE
consider adding urdfdom-tools as a dependency of metapackage robot_model

### ISSUE THREAD

**Issue by tfoote** [ros/robot_model#98]
This is a useful tools for debugging the URDF. 

Refiled from https://github.com/ros/rosdistro/issues/5956

**Comment by davetcoleman** [comment]
+1
I believe this issue is actually a regression, as its always been a part of ros-desktop-full

**Comment by jackieokay** [comment]
Fixed in a48aa284ff05bdbc7740878ea46f53715573051d

**Comment by davetcoleman** [comment]
Thanks Jackie!
